# Website Configuration
title: Navin Franklin
logo: /assets/img/headshot_circle.png
description: "Experienced Data Science Engineer with 4+ years of expertise in cloud-native data pipelines and machine learning models."
show_downloads: true
theme: jekyll-theme-minimal
author:
  name: "Navin Franklin"
  email: "your.email@example.com"
  bio: "Passionate about data-driven decision making and leveraging cloud technologies to build scalable data pipelines and impactful machine learning solutions."

# Social Links Configuration
social_links:
  linkedin: "https://www.linkedin.com/in/yourprofile"
  github: "https://github.com/yourgithub"
  twitter: "https://twitter.com/yourtwitter"
  medium: "https://medium.com/@yourmedium"   # Example - Medium profile (optional)
  instagram: "https://www.instagram.com/yourinstagram"  # Example - Instagram profile (optional)

# Resume
resume_download:
  url: "/assets/files/navin_franklin_resume.pdf"
  label: "Download Resume"

# Customization - SEO, Meta Tags & Favicon
seo:
  description: "Navin Franklin - Data Science Engineer with 4+ years of experience in AWS, Azure, and building scalable data systems."
  author: "Navin Franklin"
  twitter_card: "summary_large_image"  # Use a large image preview for Twitter (adjust if needed)

favicon: "/assets/img/favicon.ico"   # Link to your custom favicon

# Google Analytics (optional)
google_analytics: "UA-XXXXXXX-X"  # Replace with your own tracking ID if desired

# Dark Mode (optional)
theme_config:
  dark_mode: true    # Set to true for dark mode support

# Navigation Menu (optional)
navigation:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "Projects"
    url: "/projects/"
  - name: "Blog"
    url: "/blog/"
  - name: "Contact"
    url: "/contact/"

# Footer Customization (optional)
footer:
  text: "© 2024 Navin Franklin. All Rights Reserved."
  link_text: "Privacy Policy"
  link_url: "/privacy-policy/"
  
# Display the current year dynamically (optional)
date_format: "%B %d, %Y"   # Example: December 31, 2024
